### ISSUE TITLE
Task 141 - Creación de la presentación de la Semana 6

### ISSUE THREAD

**Issue by felescgon** [fitmeapp-ispp/fitmeapp-frontend#141]
La presentación tendrá que incluir los siguientes apartados:
- [x] Elevator Pitch
- [x] Modelo de negocio
- [x] Análisis de competidores
- [x] Storyboards renovados
- [x] Análisis del coste actual (ejecución de presupuestos, costes de mantenimiento, estimación de gastos e ingresos, gastos escalonados según carga de usuarios)
- [x] Retrospectiva - Situaciones adversas
- [x] Retrospectiva - Medición de riesgo de situaciones adversas
- [x] Retrospectiva - Solución final a las situaciones
- [x] Retrospectiva - Medición del impacto de la solución
- [x] Retrospectiva - Análisis de rendimiento con reconducción del mismo según las horas no asistidas a clases
- [x] Calidad del código (incluir cobertura de tests)
- [x] Vídeo del prototipo funcional
- [x] Ruta crítica de nuestro MVP
- [x] Filtrado y resultado de la primera encuesta de feedback
- [x] Acciones derivadas según feedback
- [x] Landing page
