### ISSUE TITLE
Task 178 - Creación de la presentacióon de la Semana 7

### ISSUE THREAD

**Issue by felescgon** [fitmeapp-ispp/fitmeapp-frontend#178]
La presentación tendrá que incluir los siguientes apartados:
- [x] Elevator Pitch
- [x] Modelo de negocio
- [x] Análisis de competidores
- [x] Integrantes del equipo
- [x] Storyboards renovados (con el nuevo storyboard de inversores)
- [x] Análisis del coste actual (ejecución de presupuestos, costes de mantenimiento, estimación de gastos e ingresos, gastos escalonados según carga de usuarios + *IMPORTANTE* estimación pesimista, realista y optimista de ingresos y usuarios de la aplicación a lo largo de 4 meses, 1 año, 2 años)
- [x] Vídeo del prototipo funcional (*IMPORTANTE* si no incluye el pago o registro es suspenso, es obligatorio hacer zoom para aumentar la legibilidad)
- [x] Calidad del código (incluir cobertura de tests)
- [x] Retrospectiva - Análisis de rendimiento del equipo
- [x] Retrospectiva - Análisis de calidad
- [x] Retrospectiva - Problemas YA encontrados, estado de los mismos, seguimiento de acciones de contingencia, forma y medida del problema, tiempo de medición y el objetivo esperado
- [x] Retrospectiva - Problemas nuevos, estado de los mismos, seguimiento de acciones de contingencia, forma y medida del problema, tiempo de medición y el objetivo esperado
- [x] Retrospectiva - Modelo de gestión de problemas y riesgos 1 diapo por problema
- [x] Planning del Sprint 3
- [x] Replanning del Sprint 2-3 según bugs encontrados, nuevas funcionalidades solicitadas... tiene que quedar de forma explícita LO PLANEADO EN UN PRINCIPIO y LO PLANEADO ACTUALMENTE, hay que dejar claro si algo es resultado del feedback de usuarios
- [x] Indicar actual estado de gestión de usuarios pilotos, cómo está funcionando.... 
- [x] Landing page
