### ISSUE TITLE
Task 222 - Creación de la presentación de la Semana 8

### ISSUE THREAD

**Issue by felescgon** [fitmeapp-ispp/fitmeapp-frontend#222]
La presentación tendrá que incluir los siguientes apartados:
- [x] Elevator Pitch
- [x] Modelo de negocio
- [x] Análisis de competidores
- [x] Integrantes del equipo
- [x] Anuncios (mínimo 2)
- [x] GDPR
- [x] Análisis del coste actual (ejecución de presupuestos, costes de mantenimiento, estimación de gastos e ingresos, gastos escalonados según carga de usuarios + *IMPORTANTE* estimación pesimista, realista y optimista de ingresos y usuarios de la aplicación a lo largo de 4 meses, 1 año, 2 años)
- [x] Costes derivados de las gestiones GDPR
- [x] Vídeo del prototipo funcional (*IMPORTANTE* si no incluye el pago o registro es suspenso, es obligatorio hacer zoom para aumentar la legibilidad) Se debe resaltar las mejoras según el feedback de usuarios
- [x] Calidad del código (incluir cobertura de tests)
- [x] Retrospectiva - Análisis de rendimiento del equipo
- [x] Retrospectiva - Lecciones aprendidas
- [x] Retrospectiva - Problemas YA encontrados, estado de los mismos, seguimiento de acciones de contingencia, forma y medida del problema, tiempo de medición y el objetivo esperado
- [x] Retrospectiva - Problemas nuevos, estado de los mismos, seguimiento de acciones de contingencia, forma y medida del problema, tiempo de medición y el objetivo esperado
- [x] Retrospectiva - Modelo de gestión de problemas y riesgos
- [x] Riesgos
- [x] Planificación Sprint 3
- [x] Plan de gestión para la campaña del entregable siguiente orientado a la campaña de lanzamiento y replanificación según feedback del usuario
- [x] Indicar el feedback recibido
- [x] Landing page
