### ISSUE TITLE
Task 274 - Creación de la presentación de la Semana 9

### ISSUE THREAD

**Issue by felescgon** [fitmeapp-ispp/fitmeapp-frontend#274]
La presentación tendrá que incluir los siguientes apartados:
- [ ] Elevator Pitch
- [ ] Análisis de competidores (visión general con diferencias principales)
- [ ] Integrantes del equipo en una única diapositiva indicando quién hace de DPO
- [x] Anuncio orientado a usuarios
- [x] Storyboard de inversores
- [ ] Análisis del coste actual (ejecución de presupuestos, costes de mantenimiento, estimación de gastos e ingresos, gastos escalonados según carga de usuarios + *IMPORTANTE* estimación pesimista, realista y optimista de ingresos y usuarios de la aplicación a lo largo de 4 meses, 1 año, 2 años)
- [ ] Costes derivados de las gestiones GDPR en los costes de mantenimiento
- [ ] GDPR
- [ ] Transparencia burndown frente coste estimado frente coste real
- [ ] Vídeo del prototipo funcional (*IMPORTANTE* si no incluye el pago o registro es suspenso, es obligatorio hacer zoom para aumentar la legibilidad) Se debe de mostrar la interacción que haría un usuario real
- [ ] Calidad del código (incluir cobertura de tests)
- [ ] Retrospectiva - Análisis de rendimiento del equipo (1 diapositiva de rendimiento de cada integrante en este sprint, 1 de rendimiento del integrante en todos los sprints)
- [ ] Retrospectiva - Situaciones adversas: Antiguos: evolución, nuevas acciones, si se ha alcanzado o no el objetivo.
 Nuevos: acciones, mediciones, objetivo cuantitativo basado en algo, periodo temporal a alcanzar dicho objetivo.
- [ ] Riesgos - Acciones de mitigación y acciones de contingencia
- [ ] Planificación del siguiente entregable (contiene campaña de lanzamiento y MVP final)
- [ ] Usuarios piloto - Estado actual de situación, feedback recibido y acciones que se están tomando.
- [ ] Usuarios piloto - Acciones a tomar derivadas de feedback OBLIGATORIO QUE ESTÉN PRIORIZADAS + si genera replanificación, indicarlo
- [ ] Landing page
