### ISSUE TITLE
Task 318 - Creación de checklist para la nueva presentación

### ISSUE THREAD

**Issue by Jotaeme55** [fitmeapp-ispp/fitmeapp-frontend#318]

**Comment by Jotaeme55** [comment]
Necesitamos que os miréis el feedback que está en ISPP 2021 y hagais una checklist de todo lo que tiene tener la presentación, podeis crearla en esta misma tarea y poner la estructura como se ha hecho en otras presentaciones

**Comment by beallasai** [comment]
**CAMPAÑA DE LANZAMIENTO**
- [ ] PLAN para el lanzamiento, cómo garantizar que tenga éxito.
- [ ] COSTES antes y después de la campaña, planificar también costes de ideas a futuro.
- [ ] Anuncios de usuarios e inversores, ambos enlazados en YouTube.
- [ ] Herramientas utilizadas para realizar los anuncios.
- [ ] ANUNCIOS: a quiénes se le ponen, en qué mercado nos centramos, dónde nos publicitamos, cómo nos pueden encontrar y palabras clave (SEO).
- [ ] Acciones concretas para generar expectación

**MVP**
- [ ] DEMO con historia realista y con sentido.
- [ ] DEMO con datos reales.
- [ ] DEMO con apoyo visual del rol que usa la app.
- [ ] DEMO con todo legible, optimizando duración y sin tiempos muertos.
- [ ] Enlazar la historia de la demo con el inicio efectivo.
- [ ] Pulir app según feedback.
- [ ] Enfatizar los cambios realizados por feedback de usuarios piloto y por otros motivos.
- [ ] Ya NO se centra en las retrospectivas.

**SEGÚN ÚLTIMO FEEDBACK**
- [ ] Mejorar explicación del rendimiento.
- [ ] Explicar las estimaciones claves: de dónde vienen los datos y qué cálculos se han realizado para obtenerlas.
- [ ] Mejorar el hilo argumental estructurando la presentación en bloques lógicos.
- [ ] Asegurar legibilidad de la demo en todo momento.
